# Disable ZMK Studio to ensure build success on v0.3
CONFIG_ZMK_STUDIO=n

CONFIG_ZMK_POINTING=y
CONFIG_ZMK_IDLE_TIMEOUT=30000

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_ZMK_KEYBOARD_NAME="Corne"
