# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test Build'
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == 'simon-wg'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corne_choc_pro_left", "corne_choc_pro_right"]'
      shield: '["nice_view"]'
